ALTER TABLE leads ADD COLUMN tier TEXT DEFAULT 'COLD';
ALTER TABLE leads ADD COLUMN priority INTEGER DEFAULT 0;
ALTER TABLE leads ADD COLUMN pipeline_stage INTEGER DEFAULT 0;
ALTER TABLE leads ADD COLUMN pipeline_log TEXT DEFAULT '{}';
ALTER TABLE leads ADD COLUMN entities TEXT DEFAULT '{}';
ALTER TABLE leads ADD COLUMN niche TEXT;
ALTER TABLE leads ADD COLUMN source_channel TEXT;
ALTER TABLE leads ADD COLUMN status TEXT DEFAULT 'new';
ALTER TABLE leads ADD COLUMN is_archived INTEGER DEFAULT 0;
